// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/company/internal"
)

// internalCompanyInfoDao is internal type for wrapping internal DAO implements.
type internalCompanyInfoDao = *internal.CompanyInfoDao

// companyInfoDao is the data access object for table company_info.
// You can define custom methods on it to extend its functionality as you wish.
type companyInfoDao struct {
	internalCompanyInfoDao
}

var (
	// CompanyInfo is globally public accessible object for table company_info operations.
	CompanyInfo = companyInfoDao{
		internal.NewCompanyInfoDao(),
	}
)

// Fill with you ideas below.
