// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Payment is the golang structure for table payment.
type Payment struct {
	Id                     int64       `json:"id"                     description:"主键id"`                                                                                                                                                           // 主键id
	CompanyId              int64       `json:"companyId"              description:"公司Id"`                                                                                                                                                           // 公司Id
	MerchantId             int64       `json:"merchantId"             description:"商户ID"`                                                                                                                                                           // 商户ID
	OpenApiId              int64       `json:"openApiId"              description:"使用的开放平台配置Id"`                                                                                                                                                    // 使用的开放平台配置Id
	UserId                 int64       `json:"userId"                 description:"user_id"`                                                                                                                                                        // user_id
	SubscriptionId         string      `json:"subscriptionId"         description:"订阅id（内部编号）"`                                                                                                                                                     // 订阅id（内部编号）
	GmtCreate              *gtime.Time `json:"gmtCreate"              description:"创建时间"`                                                                                                                                                           // 创建时间
	BizType                int         `json:"bizType"                description:"业务类型。1-single payment, 3-subscription"`                                                                                                                          // 业务类型。1-single payment, 3-subscription
	BizId                  string      `json:"bizId"                  description:"业务id-即商户订单号"`                                                                                                                                                    // 业务id-即商户订单号
	Currency               string      `json:"currency"               description:"货币，“SGD” “MYR” “PHP” “IDR” “THB” 与付款金额关联的货币。指定三个字母的ISO 4217货币代码"`                                                                                                // 货币，“SGD” “MYR” “PHP” “IDR” “THB” 与付款金额关联的货币。指定三个字母的ISO 4217货币代码
	PaymentId              string      `json:"paymentId"              description:"内部支付编号（系统生成唯一）"`                                                                                                                                                 // 内部支付编号（系统生成唯一）
	TotalAmount            int64       `json:"totalAmount"            description:"总计金额"`                                                                                                                                                           // 总计金额
	PaymentAmount          int64       `json:"paymentAmount"          description:"payment_amount"`                                                                                                                                                 // payment_amount
	BalanceAmount          int64       `json:"balanceAmount"          description:"balance_amount"`                                                                                                                                                 // balance_amount
	RefundAmount           int64       `json:"refundAmount"           description:"总共已退款金额"`                                                                                                                                                        // 总共已退款金额
	Status                 int         `json:"status"                 description:"支付状态。10-支付中，20-支付成功，30-支付取消"`                                                                                                                                    // 支付状态。10-支付中，20-支付成功，30-支付取消
	TerminalIp             string      `json:"terminalIp"             description:"实时交易终端IP"`                                                                                                                                                       // 实时交易终端IP
	CountryCode            string      `json:"countryCode"            description:"国家代码，指定发起交易的国家的两个字母的ISO 3166国家代码。目前支持SG、MY、PH、ID和TH"`                                                                                                            // 国家代码，指定发起交易的国家的两个字母的ISO 3166国家代码。目前支持SG、MY、PH、ID和TH
	AuthorizeStatus        int         `json:"authorizeStatus"        description:"用户授权状态，0-未授权，1-已授权，2-已发起捕获"`                                                                                                                                     // 用户授权状态，0-未授权，1-已授权，2-已发起捕获
	ChannelId              int64       `json:"channelId"              description:"支付方式id,表oversea_pay_channel的id"`                                                                                                                                 // 支付方式id,表oversea_pay_channel的id
	ChannelPaymentIntentId string      `json:"channelPaymentIntentId" description:"第三方支付平台支付预订单ID，支付接口返回"`                                                                                                                                          // 第三方支付平台支付预订单ID，支付接口返回
	ChannelPaymentId       string      `json:"channelPaymentId"       description:"外部支付渠道订单号，支付成功回调返回"`                                                                                                                                             // 外部支付渠道订单号，支付成功回调返回
	CaptureDelayHours      int         `json:"captureDelayHours"      description:"延迟Capture时间"`                                                                                                                                                    // 延迟Capture时间
	CreateTime             *gtime.Time `json:"createTime"             description:"支付单创建时间"`                                                                                                                                                        // 支付单创建时间
	CancelTime             *gtime.Time `json:"cancelTime"             description:"支付单取消时间"`                                                                                                                                                        // 支付单取消时间
	PaidTime               *gtime.Time `json:"paidTime"               description:"付款成功时间"`                                                                                                                                                         // 付款成功时间
	InvoiceId              string      `json:"invoiceId"              description:"发票号"`                                                                                                                                                            // 发票号
	GmtModify              *gtime.Time `json:"gmtModify"              description:"更新时间"`                                                                                                                                                           // 更新时间
	AppId                  string      `json:"appId"                  description:"支付使用的APPID"`                                                                                                                                                     // 支付使用的APPID
	ReturnUrl              string      `json:"returnUrl"              description:"支付成功回调Url"`                                                                                                                                                      // 支付成功回调Url
	ChannelEdition         string      `json:"channelEdition"         description:"支付通道版本号"`                                                                                                                                                        // 支付通道版本号
	HidePaymentMethods     string      `json:"hidePaymentMethods"     description:"隐藏支付方式，分号隔开;枚举： “INSTALMENT” “POSTPAID” “CARD” 在 GrabPay Checkout 流程中对用户隐藏指定的支付方式。如果未设置，GrabPay 会向用户显示所有符合条件的付款方式。但是请注意，您不能隐藏 GrabPay 钱包付款方式  注意：CARD 目前仅适用于泰国"` // 隐藏支付方式，分号隔开;枚举： “INSTALMENT” “POSTPAID” “CARD” 在 GrabPay Checkout 流程中对用户隐藏指定的支付方式。如果未设置，GrabPay 会向用户显示所有符合条件的付款方式。但是请注意，您不能隐藏 GrabPay 钱包付款方式  注意：CARD 目前仅适用于泰国
	Verify                 string      `json:"verify"                 description:"codeVerify校验值"`                                                                                                                                                  // codeVerify校验值
	Code                   string      `json:"code"                   description:""`                                                                                                                                                               //
	Token                  string      `json:"token"                  description:""`                                                                                                                                                               //
	AdditionalData         string      `json:"additionalData"         description:"额外信息，JSON结构"`                                                                                                                                                    // 额外信息，JSON结构
	Link                   string      `json:"link"                   description:""`                                                                                                                                                               //
	PaymentData            string      `json:"paymentData"            description:"渠道支付接口返回核心参数，JSON结构"`                                                                                                                                            // 渠道支付接口返回核心参数，JSON结构
	UniqueId               string      `json:"uniqueId"               description:"唯一键，以同步为逻辑加入使用自定义唯一键"`                                                                                                                                           // 唯一键，以同步为逻辑加入使用自定义唯一键
	BalanceStart           int64       `json:"balanceStart"           description:"balance_start"`                                                                                                                                                  // balance_start
	BalanceEnd             int64       `json:"balanceEnd"             description:"balance_end"`                                                                                                                                                    // balance_end
	InvoiceData            string      `json:"invoiceData"            description:""`                                                                                                                                                               //
}
