// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Subscription is the golang structure for table subscription.
type Subscription struct {
	Id                          uint64      `json:"id"                          description:""`                                                                                                                                                               //
	SubscriptionId              string      `json:"subscriptionId"              description:"subscription id"`                                                                                                                                                // subscription id
	UserId                      int64       `json:"userId"                      description:"userId"`                                                                                                                                                         // userId
	GmtCreate                   *gtime.Time `json:"gmtCreate"                   description:"create time"`                                                                                                                                                    // create time
	GmtModify                   *gtime.Time `json:"gmtModify"                   description:"update time"`                                                                                                                                                    // update time
	TaskTime                    *gtime.Time `json:"taskTime"                    description:"task_time"`                                                                                                                                                      // task_time
	Amount                      int64       `json:"amount"                      description:"amount, cent"`                                                                                                                                                   // amount, cent
	Currency                    string      `json:"currency"                    description:"currency"`                                                                                                                                                       // currency
	MerchantId                  int64       `json:"merchantId"                  description:"merchant id"`                                                                                                                                                    // merchant id
	PlanId                      int64       `json:"planId"                      description:"plan id"`                                                                                                                                                        // plan id
	Quantity                    int64       `json:"quantity"                    description:"quantity"`                                                                                                                                                       // quantity
	AddonData                   string      `json:"addonData"                   description:"plan addon json data"`                                                                                                                                           // plan addon json data
	LatestInvoiceId             string      `json:"latestInvoiceId"             description:"latest_invoice_id"`                                                                                                                                              // latest_invoice_id
	Type                        int         `json:"type"                        description:"sub type, 0-gateway sub, 1-unibee sub"`                                                                                                                          // sub type, 0-gateway sub, 1-unibee sub
	GatewayId                   int64       `json:"gatewayId"                   description:"gateway_id"`                                                                                                                                                     // gateway_id
	Status                      int         `json:"status"                      description:"status，0-Init | 1-Create｜2-Active｜3-PendingInActive | 4-Cancel | 5-Expire | 6- Suspend| 7-Incomplete"`                                                           // status，0-Init | 1-Create｜2-Active｜3-PendingInActive | 4-Cancel | 5-Expire | 6- Suspend| 7-Incomplete
	GatewaySubscriptionId       string      `json:"gatewaySubscriptionId"       description:"gateway subscription id"`                                                                                                                                        // gateway subscription id
	CustomerName                string      `json:"customerName"                description:"customer_name"`                                                                                                                                                  // customer_name
	CustomerEmail               string      `json:"customerEmail"               description:"customer_email"`                                                                                                                                                 // customer_email
	IsDeleted                   int         `json:"isDeleted"                   description:"0-UnDeleted，1-Deleted"`                                                                                                                                          // 0-UnDeleted，1-Deleted
	GatewayDefaultPaymentMethod string      `json:"gatewayDefaultPaymentMethod" description:""`                                                                                                                                                               //
	Link                        string      `json:"link"                        description:""`                                                                                                                                                               //
	GatewayStatus               string      `json:"gatewayStatus"               description:"gateway status，Stripe：https://stripe.com/docs/billing/subscriptions/webhooks  Paypal：https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_get"` // gateway status，Stripe：https://stripe.com/docs/billing/subscriptions/webhooks  Paypal：https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_get
	GatewayItemData             string      `json:"gatewayItemData"             description:"gateway_item_data"`                                                                                                                                              // gateway_item_data
	CancelAtPeriodEnd           int         `json:"cancelAtPeriodEnd"           description:"whether cancel at period end，0-false | 1-true"`                                                                                                                  // whether cancel at period end，0-false | 1-true
	GatewayLatestInvoiceId      string      `json:"gatewayLatestInvoiceId"      description:"gateway latest invoice id"`                                                                                                                                      // gateway latest invoice id
	LastUpdateTime              int64       `json:"lastUpdateTime"              description:""`                                                                                                                                                               //
	CurrentPeriodStart          int64       `json:"currentPeriodStart"          description:"current_period_start, utc time"`                                                                                                                                 // current_period_start, utc time
	CurrentPeriodEnd            int64       `json:"currentPeriodEnd"            description:"current_period_end, utc time"`                                                                                                                                   // current_period_end, utc time
	CurrentPeriodStartTime      *gtime.Time `json:"currentPeriodStartTime"      description:""`                                                                                                                                                               //
	CurrentPeriodEndTime        *gtime.Time `json:"currentPeriodEndTime"        description:""`                                                                                                                                                               //
	BillingCycleAnchor          int64       `json:"billingCycleAnchor"          description:"billing_cycle_anchor"`                                                                                                                                           // billing_cycle_anchor
	DunningTime                 int64       `json:"dunningTime"                 description:"dunning_time, utc time"`                                                                                                                                         // dunning_time, utc time
	TrialEnd                    int64       `json:"trialEnd"                    description:"trial_end"`                                                                                                                                                      // trial_end
	ReturnUrl                   string      `json:"returnUrl"                   description:""`                                                                                                                                                               //
	FirstPaidAt                 int64       `json:"firstPaidAt"                 description:"first success payment time"`                                                                                                                                     // first success payment time
	CancelReason                string      `json:"cancelReason"                description:""`                                                                                                                                                               //
	CountryCode                 string      `json:"countryCode"                 description:""`                                                                                                                                                               //
	VatNumber                   string      `json:"vatNumber"                   description:""`                                                                                                                                                               //
	TaxScale                    int64       `json:"taxScale"                    description:"Tax Scale，1000 = 10%"`                                                                                                                                           // Tax Scale，1000 = 10%
	VatVerifyData               string      `json:"vatVerifyData"               description:""`                                                                                                                                                               //
	Data                        string      `json:"data"                        description:""`                                                                                                                                                               //
	ResponseData                string      `json:"responseData"                description:""`                                                                                                                                                               //
	PendingUpdateId             string      `json:"pendingUpdateId"             description:""`                                                                                                                                                               //
	CreateAt                    int64       `json:"createAt"                    description:"create utc time"`                                                                                                                                                // create utc time
}
