// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalChannelUserDao is internal type for wrapping internal DAO implements.
type internalChannelUserDao = *internal.ChannelUserDao

// channelUserDao is the data access object for table channel_user.
// You can define custom methods on it to extend its functionality as you wish.
type channelUserDao struct {
	internalChannelUserDao
}

var (
	// ChannelUser is globally public accessible object for table channel_user operations.
	ChannelUser = channelUserDao{
		internal.NewChannelUserDao(),
	}
)

// Fill with you ideas below.
