// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalChannelPlanDao is internal type for wrapping internal DAO implements.
type internalChannelPlanDao = *internal.ChannelPlanDao

// channelPlanDao is the data access object for table channel_plan.
// You can define custom methods on it to extend its functionality as you wish.
type channelPlanDao struct {
	internalChannelPlanDao
}

var (
	// ChannelPlan is globally public accessible object for table channel_plan operations.
	ChannelPlan = channelPlanDao{
		internal.NewChannelPlanDao(),
	}
)

// Fill with you ideas below.
