// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalChannelVatRateDao is internal type for wrapping internal DAO implements.
type internalChannelVatRateDao = *internal.ChannelVatRateDao

// channelVatRateDao is the data access object for table channel_vat_rate.
// You can define custom methods on it to extend its functionality as you wish.
type channelVatRateDao struct {
	internalChannelVatRateDao
}

var (
	// ChannelVatRate is globally public accessible object for table channel_vat_rate operations.
	ChannelVatRate = channelVatRateDao{
		internal.NewChannelVatRateDao(),
	}
)

// Fill with you ideas below.
