// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalChannelHttpLogDao is internal type for wrapping internal DAO implements.
type internalChannelHttpLogDao = *internal.ChannelHttpLogDao

// channelHttpLogDao is the data access object for table channel_http_log.
// You can define custom methods on it to extend its functionality as you wish.
type channelHttpLogDao struct {
	internalChannelHttpLogDao
}

var (
	// ChannelHttpLog is globally public accessible object for table channel_http_log operations.
	ChannelHttpLog = channelHttpLogDao{
		internal.NewChannelHttpLogDao(),
	}
)

// Fill with you ideas below.
