// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalEmailTemplateDao is internal type for wrapping internal DAO implements.
type internalEmailTemplateDao = *internal.EmailTemplateDao

// emailTemplateDao is the data access object for table email_template.
// You can define custom methods on it to extend its functionality as you wish.
type emailTemplateDao struct {
	internalEmailTemplateDao
}

var (
	// EmailTemplate is globally public accessible object for table email_template operations.
	EmailTemplate = emailTemplateDao{
		internal.NewEmailTemplateDao(),
	}
)

// Fill with you ideas below.
