// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalEmailDefaultTemplateDao is internal type for wrapping internal DAO implements.
type internalEmailDefaultTemplateDao = *internal.EmailDefaultTemplateDao

// emailDefaultTemplateDao is the data access object for table email_default_template.
// You can define custom methods on it to extend its functionality as you wish.
type emailDefaultTemplateDao struct {
	internalEmailDefaultTemplateDao
}

var (
	// EmailDefaultTemplate is globally public accessible object for table email_default_template operations.
	EmailDefaultTemplate = emailDefaultTemplateDao{
		internal.NewEmailDefaultTemplateDao(),
	}
)

// Fill with you ideas below.
