// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalEmailHistoryDao is internal type for wrapping internal DAO implements.
type internalEmailHistoryDao = *internal.EmailHistoryDao

// emailHistoryDao is the data access object for table email_history.
// You can define custom methods on it to extend its functionality as you wish.
type emailHistoryDao struct {
	internalEmailHistoryDao
}

var (
	// EmailHistory is globally public accessible object for table email_history operations.
	EmailHistory = emailHistoryDao{
		internal.NewEmailHistoryDao(),
	}
)

// Fill with you ideas below.
