// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalFileUploadDao is internal type for wrapping internal DAO implements.
type internalFileUploadDao = *internal.FileUploadDao

// fileUploadDao is the data access object for table file_upload.
// You can define custom methods on it to extend its functionality as you wish.
type fileUploadDao struct {
	internalFileUploadDao
}

var (
	// FileUpload is globally public accessible object for table file_upload operations.
	FileUpload = fileUploadDao{
		internal.NewFileUploadDao(),
	}
)

// Fill with you ideas below.
