// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalGatewayHttpLogDao is internal type for wrapping internal DAO implements.
type internalGatewayHttpLogDao = *internal.GatewayHttpLogDao

// gatewayHttpLogDao is the data access object for table gateway_http_log.
// You can define custom methods on it to extend its functionality as you wish.
type gatewayHttpLogDao struct {
	internalGatewayHttpLogDao
}

var (
	// GatewayHttpLog is globally public accessible object for table gateway_http_log operations.
	GatewayHttpLog = gatewayHttpLogDao{
		internal.NewGatewayHttpLogDao(),
	}
)

// Fill with you ideas below.
