// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalGatewayPlanDao is internal type for wrapping internal DAO implements.
type internalGatewayPlanDao = *internal.GatewayPlanDao

// gatewayPlanDao is the data access object for table gateway_plan.
// You can define custom methods on it to extend its functionality as you wish.
type gatewayPlanDao struct {
	internalGatewayPlanDao
}

var (
	// GatewayPlan is globally public accessible object for table gateway_plan operations.
	GatewayPlan = gatewayPlanDao{
		internal.NewGatewayPlanDao(),
	}
)

// Fill with you ideas below.
