// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalGatewayVatRateDao is internal type for wrapping internal DAO implements.
type internalGatewayVatRateDao = *internal.GatewayVatRateDao

// gatewayVatRateDao is the data access object for table gateway_vat_rate.
// You can define custom methods on it to extend its functionality as you wish.
type gatewayVatRateDao struct {
	internalGatewayVatRateDao
}

var (
	// GatewayVatRate is globally public accessible object for table gateway_vat_rate operations.
	GatewayVatRate = gatewayVatRateDao{
		internal.NewGatewayVatRateDao(),
	}
)

// Fill with you ideas below.
