// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalInvoiceDao is internal type for wrapping internal DAO implements.
type internalInvoiceDao = *internal.InvoiceDao

// invoiceDao is the data access object for table invoice.
// You can define custom methods on it to extend its functionality as you wish.
type invoiceDao struct {
	internalInvoiceDao
}

var (
	// Invoice is globally public accessible object for table invoice operations.
	Invoice = invoiceDao{
		internal.NewInvoiceDao(),
	}
)

// Fill with you ideas below.
