// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalMerchantUserAccountDao is internal type for wrapping internal DAO implements.
type internalMerchantUserAccountDao = *internal.MerchantUserAccountDao

// merchantUserAccountDao is the data access object for table merchant_user_account.
// You can define custom methods on it to extend its functionality as you wish.
type merchantUserAccountDao struct {
	internalMerchantUserAccountDao
}

var (
	// MerchantUserAccount is globally public accessible object for table merchant_user_account operations.
	MerchantUserAccount = merchantUserAccountDao{
		internal.NewMerchantUserAccountDao(),
	}
)

// Fill with you ideas below.
