// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalMerchantPayChannelMappingDao is internal type for wrapping internal DAO implements.
type internalMerchantPayChannelMappingDao = *internal.MerchantPayChannelMappingDao

// merchantPayChannelMappingDao is the data access object for table merchant_pay_channel_mapping.
// You can define custom methods on it to extend its functionality as you wish.
type merchantPayChannelMappingDao struct {
	internalMerchantPayChannelMappingDao
}

var (
	// MerchantPayChannelMapping is globally public accessible object for table merchant_pay_channel_mapping operations.
	MerchantPayChannelMapping = merchantPayChannelMappingDao{
		internal.NewMerchantPayChannelMappingDao(),
	}
)

// Fill with you ideas below.
