// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalMerchantInfoDao is internal type for wrapping internal DAO implements.
type internalMerchantInfoDao = *internal.MerchantInfoDao

// merchantInfoDao is the data access object for table merchant_info.
// You can define custom methods on it to extend its functionality as you wish.
type merchantInfoDao struct {
	internalMerchantInfoDao
}

var (
	// MerchantInfo is globally public accessible object for table merchant_info operations.
	MerchantInfo = merchantInfoDao{
		internal.NewMerchantInfoDao(),
	}
)

// Fill with you ideas below.
