// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantDiscountCodeDao is internal type for wrapping internal DAO implements.
type internalMerchantDiscountCodeDao = *internal.MerchantDiscountCodeDao

// merchantDiscountCodeDao is the data access object for table merchant_discount_code.
// You can define custom methods on it to extend its functionality as you wish.
type merchantDiscountCodeDao struct {
	internalMerchantDiscountCodeDao
}

var (
	// MerchantDiscountCode is globally public accessible object for table merchant_discount_code operations.
	MerchantDiscountCode = merchantDiscountCodeDao{
		internal.NewMerchantDiscountCodeDao(),
	}
)

// Fill with you ideas below.
