// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantBatchExportTemplateDao is internal type for wrapping internal DAO implements.
type internalMerchantBatchExportTemplateDao = *internal.MerchantBatchExportTemplateDao

// merchantBatchExportTemplateDao is the data access object for table merchant_batch_export_template.
// You can define custom methods on it to extend its functionality as you wish.
type merchantBatchExportTemplateDao struct {
	internalMerchantBatchExportTemplateDao
}

var (
	// MerchantBatchExportTemplate is globally public accessible object for table merchant_batch_export_template operations.
	MerchantBatchExportTemplate = merchantBatchExportTemplateDao{
		internal.NewMerchantBatchExportTemplateDao(),
	}
)

// Fill with you ideas below.
