// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalMerchantAccountMainDao is internal type for wrapping internal DAO implements.
type internalMerchantAccountMainDao = *internal.MerchantAccountMainDao

// merchantAccountMainDao is the data access object for table merchant_account_main.
// You can define custom methods on it to extend its functionality as you wish.
type merchantAccountMainDao struct {
	internalMerchantAccountMainDao
}

var (
	// MerchantAccountMain is globally public accessible object for table merchant_account_main operations.
	MerchantAccountMain = merchantAccountMainDao{
		internal.NewMerchantAccountMainDao(),
	}
)

// Fill with you ideas below.
