// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalMerchantAccountOrderDao is internal type for wrapping internal DAO implements.
type internalMerchantAccountOrderDao = *internal.MerchantAccountOrderDao

// merchantAccountOrderDao is the data access object for table merchant_account_order.
// You can define custom methods on it to extend its functionality as you wish.
type merchantAccountOrderDao struct {
	internalMerchantAccountOrderDao
}

var (
	// MerchantAccountOrder is globally public accessible object for table merchant_account_order operations.
	MerchantAccountOrder = merchantAccountOrderDao{
		internal.NewMerchantAccountOrderDao(),
	}
)

// Fill with you ideas below.
