// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantWebhookDao is internal type for wrapping internal DAO implements.
type internalMerchantWebhookDao = *internal.MerchantWebhookDao

// merchantWebhookDao is the data access object for table merchant_webhook.
// You can define custom methods on it to extend its functionality as you wish.
type merchantWebhookDao struct {
	internalMerchantWebhookDao
}

var (
	// MerchantWebhook is globally public accessible object for table merchant_webhook operations.
	MerchantWebhook = merchantWebhookDao{
		internal.NewMerchantWebhookDao(),
	}
)

// Fill with you ideas below.
