// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalMerchantVatNumberVerifyHistoryDao is internal type for wrapping internal DAO implements.
type internalMerchantVatNumberVerifyHistoryDao = *internal.MerchantVatNumberVerifyHistoryDao

// merchantVatNumberVerifyHistoryDao is the data access object for table merchant_vat_number_verify_history.
// You can define custom methods on it to extend its functionality as you wish.
type merchantVatNumberVerifyHistoryDao struct {
	internalMerchantVatNumberVerifyHistoryDao
}

var (
	// MerchantVatNumberVerifyHistory is globally public accessible object for table merchant_vat_number_verify_history operations.
	MerchantVatNumberVerifyHistory = merchantVatNumberVerifyHistoryDao{
		internal.NewMerchantVatNumberVerifyHistoryDao(),
	}
)

// Fill with you ideas below.
