// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalMerchantEmailTemplateDao is internal type for wrapping internal DAO implements.
type internalMerchantEmailTemplateDao = *internal.MerchantEmailTemplateDao

// merchantEmailTemplateDao is the data access object for table merchant_email_template.
// You can define custom methods on it to extend its functionality as you wish.
type merchantEmailTemplateDao struct {
	internalMerchantEmailTemplateDao
}

var (
	// MerchantEmailTemplate is globally public accessible object for table merchant_email_template operations.
	MerchantEmailTemplate = merchantEmailTemplateDao{
		internal.NewMerchantEmailTemplateDao(),
	}
)

// Fill with you ideas below.
