// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantGatewayDao is internal type for wrapping internal DAO implements.
type internalMerchantGatewayDao = *internal.MerchantGatewayDao

// merchantGatewayDao is the data access object for table merchant_gateway.
// You can define custom methods on it to extend its functionality as you wish.
type merchantGatewayDao struct {
	internalMerchantGatewayDao
}

var (
	// MerchantGateway is globally public accessible object for table merchant_gateway operations.
	MerchantGateway = merchantGatewayDao{
		internal.NewMerchantGatewayDao(),
	}
)

// Fill with you ideas below.
