// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantPayGatewayBindingDao is internal type for wrapping internal DAO implements.
type internalMerchantPayGatewayBindingDao = *internal.MerchantPayGatewayBindingDao

// merchantPayGatewayBindingDao is the data access object for table merchant_pay_gateway_binding.
// You can define custom methods on it to extend its functionality as you wish.
type merchantPayGatewayBindingDao struct {
	internalMerchantPayGatewayBindingDao
}

var (
	// MerchantPayGatewayBinding is globally public accessible object for table merchant_pay_gateway_binding operations.
	MerchantPayGatewayBinding = merchantPayGatewayBindingDao{
		internal.NewMerchantPayGatewayBindingDao(),
	}
)

// Fill with you ideas below.
