// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantMemberDao is internal type for wrapping internal DAO implements.
type internalMerchantMemberDao = *internal.MerchantMemberDao

// merchantMemberDao is the data access object for table merchant_member.
// You can define custom methods on it to extend its functionality as you wish.
type merchantMemberDao struct {
	internalMerchantMemberDao
}

var (
	// MerchantMember is globally public accessible object for table merchant_member operations.
	MerchantMember = merchantMemberDao{
		internal.NewMerchantMemberDao(),
	}
)

// Fill with you ideas below.
