// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalMerchantWebhookLogDao is internal type for wrapping internal DAO implements.
type internalMerchantWebhookLogDao = *internal.MerchantWebhookLogDao

// merchantWebhookLogDao is the data access object for table merchant_webhook_log.
// You can define custom methods on it to extend its functionality as you wish.
type merchantWebhookLogDao struct {
	internalMerchantWebhookLogDao
}

var (
	// MerchantWebhookLog is globally public accessible object for table merchant_webhook_log operations.
	MerchantWebhookLog = merchantWebhookLogDao{
		internal.NewMerchantWebhookLogDao(),
	}
)

// Fill with you ideas below.
