// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalMerchantVatNumberValicationHistoryDao is internal type for wrapping internal DAO implements.
type internalMerchantVatNumberValicationHistoryDao = *internal.MerchantVatNumberValicationHistoryDao

// merchantVatNumberValicationHistoryDao is the data access object for table merchant_vat_number_valication_history.
// You can define custom methods on it to extend its functionality as you wish.
type merchantVatNumberValicationHistoryDao struct {
	internalMerchantVatNumberValicationHistoryDao
}

var (
	// MerchantVatNumberValicationHistory is globally public accessible object for table merchant_vat_number_valication_history operations.
	MerchantVatNumberValicationHistory = merchantVatNumberValicationHistoryDao{
		internal.NewMerchantVatNumberValicationHistoryDao(),
	}
)

// Fill with you ideas below.
