// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalMerchantChannelConfigDao is internal type for wrapping internal DAO implements.
type internalMerchantChannelConfigDao = *internal.MerchantChannelConfigDao

// merchantChannelConfigDao is the data access object for table merchant_channel_config.
// You can define custom methods on it to extend its functionality as you wish.
type merchantChannelConfigDao struct {
	internalMerchantChannelConfigDao
}

var (
	// MerchantChannelConfig is globally public accessible object for table merchant_channel_config operations.
	MerchantChannelConfig = merchantChannelConfigDao{
		internal.NewMerchantChannelConfigDao(),
	}
)

// Fill with you ideas below.
