// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalOpenApiConfigDao is internal type for wrapping internal DAO implements.
type internalOpenApiConfigDao = *internal.OpenApiConfigDao

// openApiConfigDao is the data access object for table open_api_config.
// You can define custom methods on it to extend its functionality as you wish.
type openApiConfigDao struct {
	internalOpenApiConfigDao
}

var (
	// OpenApiConfig is globally public accessible object for table open_api_config operations.
	OpenApiConfig = openApiConfigDao{
		internal.NewOpenApiConfigDao(),
	}
)

// Fill with you ideas below.
