// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalOverseaPayChannelDao is internal type for wrapping internal DAO implements.
type internalOverseaPayChannelDao = *internal.OverseaPayChannelDao

// overseaPayChannelDao is the data access object for table oversea_pay_channel.
// You can define custom methods on it to extend its functionality as you wish.
type overseaPayChannelDao struct {
	internalOverseaPayChannelDao
}

var (
	// OverseaPayChannel is globally public accessible object for table oversea_pay_channel operations.
	OverseaPayChannel = overseaPayChannelDao{
		internal.NewOverseaPayChannelDao(),
	}
)

// Fill with you ideas below.
