// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalOverseaPayDao is internal type for wrapping internal DAO implements.
type internalOverseaPayDao = *internal.OverseaPayDao

// overseaPayDao is the data access object for table oversea_pay.
// You can define custom methods on it to extend its functionality as you wish.
type overseaPayDao struct {
	internalOverseaPayDao
}

var (
	// OverseaPay is globally public accessible object for table oversea_pay operations.
	OverseaPay = overseaPayDao{
		internal.NewOverseaPayDao(),
	}
)

// Fill with you ideas below.
