// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalOverseaRefundDao is internal type for wrapping internal DAO implements.
type internalOverseaRefundDao = *internal.OverseaRefundDao

// overseaRefundDao is the data access object for table oversea_refund.
// You can define custom methods on it to extend its functionality as you wish.
type overseaRefundDao struct {
	internalOverseaRefundDao
}

var (
	// OverseaRefund is globally public accessible object for table oversea_refund operations.
	OverseaRefund = overseaRefundDao{
		internal.NewOverseaRefundDao(),
	}
)

// Fill with you ideas below.
