// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalOverseaPayEventDao is internal type for wrapping internal DAO implements.
type internalOverseaPayEventDao = *internal.OverseaPayEventDao

// overseaPayEventDao is the data access object for table oversea_pay_event.
// You can define custom methods on it to extend its functionality as you wish.
type overseaPayEventDao struct {
	internalOverseaPayEventDao
}

var (
	// OverseaPayEvent is globally public accessible object for table oversea_pay_event operations.
	OverseaPayEvent = overseaPayEventDao{
		internal.NewOverseaPayEventDao(),
	}
)

// Fill with you ideas below.
