// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalPaymentItemDao is internal type for wrapping internal DAO implements.
type internalPaymentItemDao = *internal.PaymentItemDao

// paymentItemDao is the data access object for table payment_item.
// You can define custom methods on it to extend its functionality as you wish.
type paymentItemDao struct {
	internalPaymentItemDao
}

var (
	// PaymentItem is globally public accessible object for table payment_item operations.
	PaymentItem = paymentItemDao{
		internal.NewPaymentItemDao(),
	}
)

// Fill with you ideas below.
