// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalPaymentTimelineDao is internal type for wrapping internal DAO implements.
type internalPaymentTimelineDao = *internal.PaymentTimelineDao

// paymentTimelineDao is the data access object for table payment_timeline.
// You can define custom methods on it to extend its functionality as you wish.
type paymentTimelineDao struct {
	internalPaymentTimelineDao
}

var (
	// PaymentTimeline is globally public accessible object for table payment_timeline operations.
	PaymentTimeline = paymentTimelineDao{
		internal.NewPaymentTimelineDao(),
	}
)

// Fill with you ideas below.
