// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalPaymentEventDao is internal type for wrapping internal DAO implements.
type internalPaymentEventDao = *internal.PaymentEventDao

// paymentEventDao is the data access object for table payment_event.
// You can define custom methods on it to extend its functionality as you wish.
type paymentEventDao struct {
	internalPaymentEventDao
}

var (
	// PaymentEvent is globally public accessible object for table payment_event operations.
	PaymentEvent = paymentEventDao{
		internal.NewPaymentEventDao(),
	}
)

// Fill with you ideas below.
