// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee-api/internal/dao/oversea_pay/internal"
)

// internalRefundDao is internal type for wrapping internal DAO implements.
type internalRefundDao = *internal.RefundDao

// refundDao is the data access object for table refund.
// You can define custom methods on it to extend its functionality as you wish.
type refundDao struct {
	internalRefundDao
}

var (
	// Refund is globally public accessible object for table refund operations.
	Refund = refundDao{
		internal.NewRefundDao(),
	}
)

// Fill with you ideas below.
