// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalSubscriptionUserChannelDao is internal type for wrapping internal DAO implements.
type internalSubscriptionUserChannelDao = *internal.SubscriptionUserChannelDao

// subscriptionUserChannelDao is the data access object for table subscription_user_channel.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionUserChannelDao struct {
	internalSubscriptionUserChannelDao
}

var (
	// SubscriptionUserChannel is globally public accessible object for table subscription_user_channel operations.
	SubscriptionUserChannel = subscriptionUserChannelDao{
		internal.NewSubscriptionUserChannelDao(),
	}
)

// Fill with you ideas below.
