// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalSubscriptionPlanChannelDao is internal type for wrapping internal DAO implements.
type internalSubscriptionPlanChannelDao = *internal.SubscriptionPlanChannelDao

// subscriptionPlanChannelDao is the data access object for table subscription_plan_channel.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionPlanChannelDao struct {
	internalSubscriptionPlanChannelDao
}

var (
	// SubscriptionPlanChannel is globally public accessible object for table subscription_plan_channel operations.
	SubscriptionPlanChannel = subscriptionPlanChannelDao{
		internal.NewSubscriptionPlanChannelDao(),
	}
)

// Fill with you ideas below.
