// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalSubscriptionVatRateChannelDao is internal type for wrapping internal DAO implements.
type internalSubscriptionVatRateChannelDao = *internal.SubscriptionVatRateChannelDao

// subscriptionVatRateChannelDao is the data access object for table subscription_vat_rate_channel.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionVatRateChannelDao struct {
	internalSubscriptionVatRateChannelDao
}

var (
	// SubscriptionVatRateChannel is globally public accessible object for table subscription_vat_rate_channel operations.
	SubscriptionVatRateChannel = subscriptionVatRateChannelDao{
		internal.NewSubscriptionVatRateChannelDao(),
	}
)

// Fill with you ideas below.
