// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalSubscriptionDao is internal type for wrapping internal DAO implements.
type internalSubscriptionDao = *internal.SubscriptionDao

// subscriptionDao is the data access object for table subscription.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionDao struct {
	internalSubscriptionDao
}

var (
	// Subscription is globally public accessible object for table subscription operations.
	Subscription = subscriptionDao{
		internal.NewSubscriptionDao(),
	}
)

// Fill with you ideas below.
