// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalSubscriptionPlanDao is internal type for wrapping internal DAO implements.
type internalSubscriptionPlanDao = *internal.SubscriptionPlanDao

// subscriptionPlanDao is the data access object for table subscription_plan.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionPlanDao struct {
	internalSubscriptionPlanDao
}

var (
	// SubscriptionPlan is globally public accessible object for table subscription_plan operations.
	SubscriptionPlan = subscriptionPlanDao{
		internal.NewSubscriptionPlanDao(),
	}
)

// Fill with you ideas below.
