// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalSubscriptionPaymentTimelineDao is internal type for wrapping internal DAO implements.
type internalSubscriptionPaymentTimelineDao = *internal.SubscriptionPaymentTimelineDao

// subscriptionPaymentTimelineDao is the data access object for table subscription_payment_timeline.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionPaymentTimelineDao struct {
	internalSubscriptionPaymentTimelineDao
}

var (
	// SubscriptionPaymentTimeline is globally public accessible object for table subscription_payment_timeline operations.
	SubscriptionPaymentTimeline = subscriptionPaymentTimelineDao{
		internal.NewSubscriptionPaymentTimelineDao(),
	}
)

// Fill with you ideas below.
