// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/oversea_pay/internal"
)

// internalSubscriptionTimelineDao is internal type for wrapping internal DAO implements.
type internalSubscriptionTimelineDao = *internal.SubscriptionTimelineDao

// subscriptionTimelineDao is the data access object for table subscription_timeline.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionTimelineDao struct {
	internalSubscriptionTimelineDao
}

var (
	// SubscriptionTimeline is globally public accessible object for table subscription_timeline operations.
	SubscriptionTimeline = subscriptionTimelineDao{
		internal.NewSubscriptionTimelineDao(),
	}
)

// Fill with you ideas below.
