// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-oversea-pay/internal/dao/oversea_pay/internal"
)

// internalTimelineDao is internal type for wrapping internal DAO implements.
type internalTimelineDao = *internal.TimelineDao

// timelineDao is the data access object for table timeline.
// You can define custom methods on it to extend its functionality as you wish.
type timelineDao struct {
	internalTimelineDao
}

var (
	// Timeline is globally public accessible object for table timeline operations.
	Timeline = timelineDao{
		internal.NewTimelineDao(),
	}
)

// Fill with you ideas below.
