// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userProfile

import (
	"go-oversea-pay/api/userProfile"
)

type ControllerV1 struct{}

func NewV1() userProfile.IUserProfileV1 {
	return &ControllerV1{}
}
