// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalCreditTransactionDao is internal type for wrapping internal DAO implements.
type internalCreditTransactionDao = *internal.CreditTransactionDao

// creditTransactionDao is the data access object for table credit_transaction.
// You can define custom methods on it to extend its functionality as you wish.
type creditTransactionDao struct {
	internalCreditTransactionDao
}

var (
	// CreditTransaction is globally public accessible object for table credit_transaction operations.
	CreditTransaction = creditTransactionDao{
		internal.NewCreditTransactionDao(),
	}
)

// Fill with you ideas below.
