// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalCreditRefundDao is internal type for wrapping internal DAO implements.
type internalCreditRefundDao = *internal.CreditRefundDao

// creditRefundDao is the data access object for table credit_refund.
// You can define custom methods on it to extend its functionality as you wish.
type creditRefundDao struct {
	internalCreditRefundDao
}

var (
	// CreditRefund is globally public accessible object for table credit_refund operations.
	CreditRefund = creditRefundDao{
		internal.NewCreditRefundDao(),
	}
)

// Fill with you ideas below.
