// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalCreditAccountDao is internal type for wrapping internal DAO implements.
type internalCreditAccountDao = *internal.CreditAccountDao

// creditAccountDao is the data access object for table credit_account.
// You can define custom methods on it to extend its functionality as you wish.
type creditAccountDao struct {
	internalCreditAccountDao
}

var (
	// CreditAccount is globally public accessible object for table credit_account operations.
	CreditAccount = creditAccountDao{
		internal.NewCreditAccountDao(),
	}
)

// Fill with you ideas below.
