// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalCreditRechargeDao is internal type for wrapping internal DAO implements.
type internalCreditRechargeDao = *internal.CreditRechargeDao

// creditRechargeDao is the data access object for table credit_recharge.
// You can define custom methods on it to extend its functionality as you wish.
type creditRechargeDao struct {
	internalCreditRechargeDao
}

var (
	// CreditRecharge is globally public accessible object for table credit_recharge operations.
	CreditRecharge = creditRechargeDao{
		internal.NewCreditRechargeDao(),
	}
)

// Fill with you ideas below.
