// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalCreditPaymentDao is internal type for wrapping internal DAO implements.
type internalCreditPaymentDao = *internal.CreditPaymentDao

// creditPaymentDao is the data access object for table credit_payment.
// You can define custom methods on it to extend its functionality as you wish.
type creditPaymentDao struct {
	internalCreditPaymentDao
}

var (
	// CreditPayment is globally public accessible object for table credit_payment operations.
	CreditPayment = creditPaymentDao{
		internal.NewCreditPaymentDao(),
	}
)

// Fill with you ideas below.
