// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalGatewayUserDao is internal type for wrapping internal DAO implements.
type internalGatewayUserDao = *internal.GatewayUserDao

// gatewayUserDao is the data access object for table gateway_user.
// You can define custom methods on it to extend its functionality as you wish.
type gatewayUserDao struct {
	internalGatewayUserDao
}

var (
	// GatewayUser is globally public accessible object for table gateway_user operations.
	GatewayUser = gatewayUserDao{
		internal.NewGatewayUserDao(),
	}
)

// Fill with you ideas below.
