// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantOperationLogDao is internal type for wrapping internal DAO implements.
type internalMerchantOperationLogDao = *internal.MerchantOperationLogDao

// merchantOperationLogDao is the data access object for table merchant_operation_log.
// You can define custom methods on it to extend its functionality as you wish.
type merchantOperationLogDao struct {
	internalMerchantOperationLogDao
}

var (
	// MerchantOperationLog is globally public accessible object for table merchant_operation_log operations.
	MerchantOperationLog = merchantOperationLogDao{
		internal.NewMerchantOperationLogDao(),
	}
)

// Fill with you ideas below.
