// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantUserDiscountCodeDao is internal type for wrapping internal DAO implements.
type internalMerchantUserDiscountCodeDao = *internal.MerchantUserDiscountCodeDao

// merchantUserDiscountCodeDao is the data access object for table merchant_user_discount_code.
// You can define custom methods on it to extend its functionality as you wish.
type merchantUserDiscountCodeDao struct {
	internalMerchantUserDiscountCodeDao
}

var (
	// MerchantUserDiscountCode is globally public accessible object for table merchant_user_discount_code operations.
	MerchantUserDiscountCode = merchantUserDiscountCodeDao{
		internal.NewMerchantUserDiscountCodeDao(),
	}
)

// Fill with you ideas below.
