// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantEmailHistoryDao is internal type for wrapping internal DAO implements.
type internalMerchantEmailHistoryDao = *internal.MerchantEmailHistoryDao

// merchantEmailHistoryDao is the data access object for table merchant_email_history.
// You can define custom methods on it to extend its functionality as you wish.
type merchantEmailHistoryDao struct {
	internalMerchantEmailHistoryDao
}

var (
	// MerchantEmailHistory is globally public accessible object for table merchant_email_history operations.
	MerchantEmailHistory = merchantEmailHistoryDao{
		internal.NewMerchantEmailHistoryDao(),
	}
)

// Fill with you ideas below.
