// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantCountryConfigDao is internal type for wrapping internal DAO implements.
type internalMerchantCountryConfigDao = *internal.MerchantCountryConfigDao

// merchantCountryConfigDao is the data access object for table merchant_country_config.
// You can define custom methods on it to extend its functionality as you wish.
type merchantCountryConfigDao struct {
	internalMerchantCountryConfigDao
}

var (
	// MerchantCountryConfig is globally public accessible object for table merchant_country_config operations.
	MerchantCountryConfig = merchantCountryConfigDao{
		internal.NewMerchantCountryConfigDao(),
	}
)

// Fill with you ideas below.
