// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantMetricEventDao is internal type for wrapping internal DAO implements.
type internalMerchantMetricEventDao = *internal.MerchantMetricEventDao

// merchantMetricEventDao is the data access object for table merchant_metric_event.
// You can define custom methods on it to extend its functionality as you wish.
type merchantMetricEventDao struct {
	internalMerchantMetricEventDao
}

var (
	// MerchantMetricEvent is globally public accessible object for table merchant_metric_event operations.
	MerchantMetricEvent = merchantMetricEventDao{
		internal.NewMerchantMetricEventDao(),
	}
)

// Fill with you ideas below.
