// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantConfigDao is internal type for wrapping internal DAO implements.
type internalMerchantConfigDao = *internal.MerchantConfigDao

// merchantConfigDao is the data access object for table merchant_config.
// You can define custom methods on it to extend its functionality as you wish.
type merchantConfigDao struct {
	internalMerchantConfigDao
}

var (
	// MerchantConfig is globally public accessible object for table merchant_config operations.
	MerchantConfig = merchantConfigDao{
		internal.NewMerchantConfigDao(),
	}
)

// Fill with you ideas below.
