// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantMetricDao is internal type for wrapping internal DAO implements.
type internalMerchantMetricDao = *internal.MerchantMetricDao

// merchantMetricDao is the data access object for table merchant_metric.
// You can define custom methods on it to extend its functionality as you wish.
type merchantMetricDao struct {
	internalMerchantMetricDao
}

var (
	// MerchantMetric is globally public accessible object for table merchant_metric operations.
	MerchantMetric = merchantMetricDao{
		internal.NewMerchantMetricDao(),
	}
)

// Fill with you ideas below.
