// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantWebhookMessageDao is internal type for wrapping internal DAO implements.
type internalMerchantWebhookMessageDao = *internal.MerchantWebhookMessageDao

// merchantWebhookMessageDao is the data access object for table merchant_webhook_message.
// You can define custom methods on it to extend its functionality as you wish.
type merchantWebhookMessageDao struct {
	internalMerchantWebhookMessageDao
}

var (
	// MerchantWebhookMessage is globally public accessible object for table merchant_webhook_message operations.
	MerchantWebhookMessage = merchantWebhookMessageDao{
		internal.NewMerchantWebhookMessageDao(),
	}
)

// Fill with you ideas below.
