// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantBatchTaskDao is internal type for wrapping internal DAO implements.
type internalMerchantBatchTaskDao = *internal.MerchantBatchTaskDao

// merchantBatchTaskDao is the data access object for table merchant_batch_task.
// You can define custom methods on it to extend its functionality as you wish.
type merchantBatchTaskDao struct {
	internalMerchantBatchTaskDao
}

var (
	// MerchantBatchTask is globally public accessible object for table merchant_batch_task operations.
	MerchantBatchTask = merchantBatchTaskDao{
		internal.NewMerchantBatchTaskDao(),
	}
)

// Fill with you ideas below.
