// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalPlanDao is internal type for wrapping internal DAO implements.
type internalPlanDao = *internal.PlanDao

// planDao is the data access object for table plan.
// You can define custom methods on it to extend its functionality as you wish.
type planDao struct {
	internalPlanDao
}

var (
	// Plan is globally public accessible object for table plan operations.
	Plan = planDao{
		internal.NewPlanDao(),
	}
)

// Fill with you ideas below.
