// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalSubscriptionAdminNoteDao is internal type for wrapping internal DAO implements.
type internalSubscriptionAdminNoteDao = *internal.SubscriptionAdminNoteDao

// subscriptionAdminNoteDao is the data access object for table subscription_admin_note.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionAdminNoteDao struct {
	internalSubscriptionAdminNoteDao
}

var (
	// SubscriptionAdminNote is globally public accessible object for table subscription_admin_note operations.
	SubscriptionAdminNote = subscriptionAdminNoteDao{
		internal.NewSubscriptionAdminNoteDao(),
	}
)

// Fill with you ideas below.
