// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalSubscriptionOnetimeAddonDao is internal type for wrapping internal DAO implements.
type internalSubscriptionOnetimeAddonDao = *internal.SubscriptionOnetimeAddonDao

// subscriptionOnetimeAddonDao is the data access object for table subscription_onetime_addon.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionOnetimeAddonDao struct {
	internalSubscriptionOnetimeAddonDao
}

var (
	// SubscriptionOnetimeAddon is globally public accessible object for table subscription_onetime_addon operations.
	SubscriptionOnetimeAddon = subscriptionOnetimeAddonDao{
		internal.NewSubscriptionOnetimeAddonDao(),
	}
)

// Fill with you ideas below.
