// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalTableUpgradeHistoryDao is internal type for wrapping internal DAO implements.
type internalTableUpgradeHistoryDao = *internal.TableUpgradeHistoryDao

// tableUpgradeHistoryDao is the data access object for table table_upgrade_history.
// You can define custom methods on it to extend its functionality as you wish.
type tableUpgradeHistoryDao struct {
	internalTableUpgradeHistoryDao
}

var (
	// TableUpgradeHistory is globally public accessible object for table table_upgrade_history operations.
	TableUpgradeHistory = tableUpgradeHistoryDao{
		internal.NewTableUpgradeHistoryDao(),
	}
)

// Fill with you ideas below.
