// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalTableUpgradeDao is internal type for wrapping internal DAO implements.
type internalTableUpgradeDao = *internal.TableUpgradeDao

// tableUpgradeDao is the data access object for table table_upgrade.
// You can define custom methods on it to extend its functionality as you wish.
type tableUpgradeDao struct {
	internalTableUpgradeDao
}

var (
	// TableUpgrade is globally public accessible object for table table_upgrade operations.
	TableUpgrade = tableUpgradeDao{
		internal.NewTableUpgradeDao(),
	}
)

// Fill with you ideas below.
